BAN_LISTS = {
    'gen9ou': [
        "Annihilape",
        "Chi-Yu",
        "Cyclizar",
        "Flutter Mane",
        "Houndstone",
        "Iron Bundle",
        "Palafin",
        "Palafin-Hero",
        "Miraidon",
        "Koraidon",
        "Chien-Pao",
        "Espathra"
    ],
    'gen9monotype': [
        "Flutter Mane",
        "Espathra",
        "Chien-Pao",
    ],
    "gen9doublesou": [
        "Annihilape",
        "Flutter Mane",
        "Koraidon",
        "Miraidon",
        "Tatsugiri",
    ],
    "gen9nationaldex": [
        "Flutter Mane",
        "Iron Bundle",
        "Koraidon",
        "Miraidon",
        "Houndstone",
        "Palafin",
        "Palafin-Hero",
        "Roaring Moon",
        "Lugia",
        "Annihilape",
        "Walking Wake",
    ],
    "gen9nationaldexmonotype": [
        "Flutter Mane",
        "Roaring Moon",
        "Spectrier",
        "Chien-Pao",
        "Espathra",
        "Darmanitan-Galar",
        "Landorus",
        "Walking Wake",
        "Regieleki",
        "Melmetal",
    ],
    "gen9uu": [
        "Pelipper",
        "Orthworm",
        "Espathra",
        "Iron Hands",
        "Iron Leaves"
    ],
    "gen9ru": [
        "Magnezone",
        "Drednaw",
        "Haxorus",
        "Kilowattrel",
        "Floatzel",
        "Polteageist",
        "Hawlucha",
        "Flamigo",
        "Toxtricity",
        "Toxtricity-Low-Key",
        "Polteageist-Antique",
        "Lycanroc-Dusk",
        "Hariyama",
    ],
}
BAN_LISTS["gen9uu"] = BAN_LISTS["gen9uu"] + BAN_LISTS["gen9ou"]
BAN_LISTS["gen9ru"] = BAN_LISTS["gen9ru"] + BAN_LISTS["gen9uu"]